name: Deploy SendStatistics Lambda Function

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      # Step 3: Install dependencies (if any)
      - name: Install dependencies
        run: |
          if [ -f "aws/lambda/SendStatistics/requirements.txt" ]; then
            pip install -r aws/lambda/SendStatistics/requirements.txt -t .
          fi

      - name: Zip Lambda function
        run: |
          cd aws/lambda/SendStatistics
          zip -r ../../../SendStatistics_lambda_function.zip .

      # Step 5: Parse the config file and find the layers
      - name: Parse layer config file
        id: parse_layers
        run: |
          layers=$(jq -r '.layers[]' aws/lambda/SendStatistics/lambda.config.json)
          echo "::set-output name=layers::$layers"

      # Step 6: Get Lambda Layer ARNs (with error handling)
      - name: Get Lambda Layer ARNs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_LAMBDA_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_LAMBDA_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        id: get_layer_arns
        run: |
          layer_arns=""
          for layer in ${{ steps.parse_layers.outputs.layers }}; do
            layer_version=$(aws lambda list-layer-versions --layer-name $layer --query 'LayerVersions[0].LayerVersionArn' --output text)
            layer_arns="$layer_arns $layer_version"
          done
          echo "::set-output name=layer_arns::$layer_arns"

      # Step 7: Deploy to AWS Lambda
      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_LAMBDA_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_LAMBDA_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          # Step 7a: Update the Lambda function code
          aws lambda update-function-code \
            --function-name ${{ secrets.SENDSTATISTICS_LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://SendStatistics_lambda_function.zip

          # Step 7b: Wait for the Lambda code update to complete
          aws lambda wait function-updated \
            --function-name ${{ secrets.SENDSTATISTICS_LAMBDA_FUNCTION_NAME }}

          # Step 7c: Update the Lambda function configuration (attach layers)
          aws lambda update-function-configuration \
            --function-name ${{ secrets.SENDSTATISTICS_LAMBDA_FUNCTION_NAME }} \
            --layers ${{ steps.get_layer_arns.outputs.layer_arns }}
