name: Deploy Lambda Function

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      # Step 3: Install dependencies (if any)
      - name: Install dependencies
        run: |
          if [ -f "aws/lambda/UserCreate/requirements.txt" ]; then
            pip install -r aws/lambda/UserCreate/requirements.txt -t .
          fi

      # Step 4: Package the Lambda function into a zip file
      - name: Zip Lambda function
        run: zip -r UserCreate_lambda_function.zip ./aws/lambda/UserCreate

      # Step 5: Deploy to AWS Lambda using AWS CLI
      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.USERCREATE_LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://UserCreate_lambda_function.zip
